name: gha-trigger step summary
description: gha-trigger step summary
inputs:
  data:
    description: gha-trigger's workflow dispatch input
    required: true
runs:
  using: composite
  steps:
    - run: echo "[Pull Request]($PR_URL)" >> "$GITHUB_STEP_SUMMARY"
      shell: bash
      env:
        PR_URL: https://github.com/${{fromJSON(inputs.data).github.repository}}/pull/${{fromJSON(inputs.data).github.event.pull_request.number}}

    - shell: bash
      run: |
        cat << 'EOS' | sed "s|PR_URL|$PR_URL|g" | sed "s|GITHUB_RUN_ID|$GITHUB_RUN_ID|g" >> "$GITHUB_STEP_SUMMARY"

        ## How to rerun or cancel the Workflow and jobs
        
        Please post a comment to the [Pull Request](PR_URL).

        Rerun the workflow.

        ```
        /rerun-workflow GITHUB_RUN_ID
        ```

        Rerun failed jobs.

        ```
        /rerun-failed-job GITHUB_RUN_ID
        ```

        Cancel the workflow.

        ```
        /cancel GITHUB_RUN_ID
        ```
        EOS
      env:
        PR_URL: https://github.com/${{fromJSON(inputs.data).github.repository}}/pull/${{fromJSON(inputs.data).github.event.pull_request.number}}
