name: gha-trigger step summary
description: gha-trigger step summary
inputs:
  data:
    description: gha-trigger's workflow dispatch input
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      if: fromJSON(inputs.data).event.pull_request.html_url
      run: |
        cat << EOS >> "$GITHUB_STEP_SUMMARY"

        [Pull Request]($PR_URL)

        ## How to rerun or cancel the Workflow and jobs
        
        Please post a comment to the [Pull Request]($PR_URL).

        Rerun the workflow.

        $CODE_BLOCK
        /rerun-workflow $GITHUB_RUN_ID
        $CODE_BLOCK

        Rerun failed jobs.

        $CODE_BLOCK
        /rerun-failed-job $GITHUB_RUN_ID
        $CODE_BLOCK

        Cancel the workflow.

        $CODE_BLOCK
        /cancel $GITHUB_RUN_ID
        $CODE_BLOCK
        EOS
      env:
        PR_URL: ${{fromJSON(inputs.data).event.pull_request.html_url}}
        CODE_BLOCK: "```"
    - shell: bash
      if: "! fromJSON(inputs.data).event.pull_request.html_url"
      run: |
        cat << EOS >> "$GITHUB_STEP_SUMMARY"

        ## How to rerun or cancel the Workflow and jobs
        
        Please post a comment to any this repository's issue or pull request.

        Rerun the workflow.

        $CODE_BLOCK
        /rerun-workflow $GITHUB_RUN_ID
        $CODE_BLOCK

        Rerun failed jobs.

        $CODE_BLOCK
        /rerun-failed-job $GITHUB_RUN_ID
        $CODE_BLOCK

        Cancel the workflow.

        $CODE_BLOCK
        /cancel $GITHUB_RUN_ID
        $CODE_BLOCK
        EOS
      env:
        CODE_BLOCK: "```"
